site_name: PalletWorks User Guide
site_url: https://docs.palletworks.app/

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite

theme:
  name: material
  features:
      - navigation.tabs
  favicon: images/favicon.ico
  palette:
    - primary: deep orange
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode

use_directory_urls: false

plugins:
  - search

nav:
    - Home:
        - Overview: index.md
        - Definitions: definitions.md
        - Components: components.md
        - Installation: installation.md
        - Global Configuration: configuration.md
        - Production Line Options: productionlineoptions.md
        - Production Line Setup: adminsetup.md
        - Status Levels: statuslevels.md
        - Services: services.md
        - Getting Started: gettingstarted.md
        - Printing: printing.md       
        - Procedures: procedures.md
        - Licensing: licensing.md
        - Service Logs: servicelogs.md
        - Support: support.md
        - About: about.md
