site_name: PalletWorks User Guide
site_url: https://docs.palletworks.app/
# repo_name: cybertrol-engineering/CE.PalletWorks.Documentation
# repo_url: https://github.com/cybertrol-engineering/CE.PalletWorks.Documentation

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite

theme:
  name: material
  features:
      - navigation.tabs
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode

use_directory_urls: false

plugins:
  - search
  - git-revision-date

nav:
    - Home:
        - Overview: index.md
        - Installation: installation.md
        - Configuration: configuration.md
        - Getting Started: gettingstarted.md
        - Procedures: procedures.md
        - Support: support.md
